### ISSUE TITLE
Segmentation fault on rclcpp::node::get_logger

### ISSUE THREAD

**Issue by Jack-ReframeSystems** [ros-controls/gz_ros2_control#130]
Line of segmentation fault: https://github.com/ros-controls/gz_ros2_control/blob/55dd7680ff7234c825efa1dd0c104e5629448972/gz_ros2_control/src/gz_ros2_control_plugin.cpp#L268

I am getting a segmentation fault when the logger is being accessed on this line, I believe it is because dataPtr->node_ is not initialized untiil line 342 of this file.

**Comment by ahcorde** [comment]
PR https://github.com/ros-controls/gz_ros2_control/pull/136
