### ISSUE TITLE
Install include directory ign_ros2_control

### ISSUE THREAD

**Issue by brenda1602** [ros-controls/gz_ros2_control#160]
Hi, 
I'm creating a custom ign_ros2_control plugin for a simulation in ROS Humble. According to the instructions, the plugin must inherit the `ign_ros2_control::IgnitionSystemInterface` class, which implements a simulated ros2_control `hardware_interface::SystemInterface`, but the package `ign_ros2_control` does not export its directory and this makes it impossible to use the class inside my plugin. 

I would like to know why the `humble` branch the install is not done as it was done with the `master` branch #127

**Comment by ahcorde** [comment]
hi @brenda1602 

Backported here https://github.com/ros-controls/gz_ros2_control/pull/161#pullrequestreview-1474785053

**Comment by ahcorde** [comment]
it's not released yet, but if you compile from source, it should work. Feel free to reopen the issue if the PR doesn't solve the issue.

**Comment by brenda1602** [comment]
Hi, @ahcorde 

Thanks for the answer,  but I will ask you to include one slash '/' at the end of the word 'include', because, without it, the cmake creates a new directory include, as the image below presents.
![image](https://github.com/ros-controls/gz_ros2_control/assets/56440570/ba3bc3b5-bd3a-4356-8ddd-28340bba7754). 

```
install(DIRECTORY
  include/
  DESTINATION include
)
```

**Comment by bmagyar** [comment]
Fyi @ahcorde

**Comment by ahcorde** [comment]
Done here https://github.com/ros-controls/gz_ros2_control/pull/162

**Comment by brenda1602** [comment]
Thank you, now it is working.
