### ISSUE TITLE
colcon build error : has no member named ‘hardware_plugin_name

### ISSUE THREAD

**Issue by Shuke-rrrw** [ros-controls/gz_ros2_control#177]
when i colcon build,it throw the error following:
error: ‘__gnu_cxx::__alloc_traits<std::allocator<hardware_interface::HardwareInfo>, hardware_interface::HardwareInfo>::value_type’ {aka ‘struct hardware_interface::HardwareInfo’} has no member named ‘hardware_plugin_name’
  404 | d::string robot_hw_sim_type_str_ = control_hardware_info[i].hardware_plugin_name;

solution:change control_hardware_info[i].hardware_plugin_name to control_hardware_info[i].name;

**Comment by bmagyar** [comment]
You could also use the appropriate branch of this plugin for the distro you use ;)
