### ISSUE TITLE
How to change controller manager node name?

### ISSUE THREAD

**Issue by delihus** [ros-controls/gz_ros2_control#187]
Is the parameter `controller_manager_prefix_node_name` in the urdf is still in use?

It looks like not.
https://github.com/ros-controls/gz_ros2_control/blob/master/gz_ros2_control/src/gz_ros2_control_plugin.cpp#L298

Is there any another way to do it?

**Comment by ahcorde** [comment]
PR is merge and forward ported to `iron` and `rolling` https://github.com/ros-controls/gz_ros2_control/pull/212
