### ISSUE TITLE
ign_ros2_control fail to build [humble]

### ISSUE THREAD

**Issue by carlospereira179** [ros-controls/gz_ros2_control#229]
I encountered this issue when building this package on the humble branch. 

`.../gz_ros2_control/ign_ros2_control/src/ign_ros2_control_plugin.cpp:382:33: error: no matching function for call to ‘hardware_interface::ResourceManager::load_urdf(std::string&, bool, bool)’
  382 |     resource_manager_->load_urdf(urdf_string, false, false);
      |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~
`

The error seems to be with one extra boolean argument on that `load_urdf` method. The log also show this:

`/opt/ros/humble/include/hardware_interface/resource_manager.hpp:84:8: note: candidate: ‘void hardware_interface::ResourceManager::load_urdf(const string&, bool)’
   84 |   void load_urdf(const std::string & urdf, bool validate_interfaces = true);
      |        ^~~~~~~~~
`
[check here](https://github.com/ros-controls/ros2_control/blob/3309c6dbaf4ab5140d13908bedb6fb471c422498/hardware_interface/src/resource_manager.cpp#L759-L796)

I deleted one of the "false" arguments and the package builds just fine

**Comment by ahcorde** [comment]
related with this other issue https://github.com/ros-controls/gz_ros2_control/issues/228
