### ISSUE TITLE
`<robot_param>` and `<robot_param_node>` tags do not work with `ign_ros2_control` plugin

### ISSUE THREAD

**Issue by rachit-aggarwal** [ros-controls/gz_ros2_control#274]
I am currently using ROS Humble + Ign Fortress and trying to load `ign_ros2_control` plugin using Ign Fortress. I am defining my own robot param parameter node as shown below using the instructions in [documentation](https://control.ros.org/humble/doc/gz_ros2_control/doc/index.html#add-the-gz-ros2-control-plugin) (I changed the plugin to ign as I am using Fortress)

```
<plugin filename="ign_ros2_control-system" name="ign_ros2_control::IgnitionROS2ControlPlugin">
  <parameters>$(find my_description)/config/default_controller.yaml</parameters>
  <robot_param>robot_description</robot_param>
  <robot_param_node>my_robot_state_publisher</robot_param_node>
</plugin>
```
I get the following error:
```
[ERROR] [1712874118.400169640] [gz_ros2_control]: robot_state_publisher service not available, waiting again...
```

It seems that the plugin is trying to access param in default node name `robot_state_publisher` and not the prescribed node name `my_robot_state_publisher`. Upon looking up in the [source](https://github.com/ros-controls/gz_ros2_control/blob/5bfa3a4624c847edd54e358f0278a5b677d20f0c/ign_ros2_control/src/ign_ros2_control_plugin.cpp#L99), it seems that the plugin tags were never added. The same `TODO` is present in the `master`/`rolling` and `iron` branches.

Can the maintainers confirm issue of missing feature or help point out if I am missing something?

**Comment by ahcorde** [comment]
@rachit-aggarwal This PR https://github.com/ros-controls/gz_ros2_control/pull/275 should fix your issues
