### ISSUE TITLE
Failed to load system plugin [gz_ros2_control-system] 

### ISSUE THREAD

**Issue by Luczia** [ros-controls/gz_ros2_control#98]
Hi,

I have the following error when launching ` ros2 launch gz_ros2_control_demos diff_drive_example.launch.py` : 

`[ign gazebo-1] Library [/colcon_ws/install/gz_ros2_control/lib/libgz_ros2_control-system.so] does not export any plugins. The symbol [IgnitionPluginHook] is missing, or it is not externally visible.   `
`[ign gazebo-1] [Err] [SystemLoader.cc:87] Failed to load system plugin [gz_ros2_control-system] : couldn't load library on path [/colcon_ws/install/gz_ros2_control/lib/libgz_ros2_control-system.so]. `

OS Version: WSL with Ubuntu 22.4
Using Docker image : Ubuntu 22.04 + ROS2 Humble + Gazebo Garden (installed from debs)

Behavior : 

Gazebo (ex Ignition) launches successfully but with that error message. As such, many controllers and topics are missing and I can't control the robot.

I am also suprised that in the roslaunch console, the node is still called "ign gazebo".

![image](https://user-images.githubusercontent.com/7024554/203389082-116783a7-359f-406e-937e-a8e3cf52d463.png)

Steps to reproduce : 

- Clone the repo https://github.com/ros-controls/gz_ros2_control.git and checkout to branch ign_to_gz
- colcon build in a ROS2 workspace

I've tried to change different plugin_names and file_names in the  urdf but without success. Any idea ? I see that the branch ign_to_gz has been updated a few hours ago but with the same behavior. 

Thanks !

I attach the Dockerfile for reproduction
[Dockerfile.humble-full-gz.txt](https://github.com/ros-controls/gz_ros2_control/files/10069923/Dockerfile.humble-full-gz.txt)

**Comment by ahcorde** [comment]
Please check these two answer https://github.com/ros-controls/gz_ros2_control/pull/67#issuecomment-1322727849 and https://github.com/ros-controls/gz_ros2_control/pull/67#issuecomment-1322727849

For following issues or PR, please don't use images, these are not searchable.

If this solve your problem please close this issue.

**Comment by Luczia** [comment]
Ok, I've rebuilt my humble image and recompiled [ros_gz](https://github.com/gazebosim/ros_gz/tree/humble) on the humble branch and it now works.

Thanks !
